### PR TITLE
add note about GDAL building issues on Windows

### PR DESCRIPTION
**Pull request by vlandau**
Some Omniscape users had this problem. Just thought I'd add text to provide some guidance. See Circuitscape/Omniscape.jl/issues/47

### CODE REVIEW

**Comment by vlandau** [comment]
@ranjanan please merge if it looks okay -- just a simple addition to the readme.

**Comment by ViralBShah** [comment]
My suggestion is that we just wait for GDAL.jl folks to tag a new version and update our dependencies.

**Comment by vlandau** [comment]
> My suggestion is that we just wait for GDAL.jl folks to tag a new version and update our dependencies.

Okay -- We don't have a compat entry for GDAL since we depend on ArchGDAL, but I _think_ this is solved with ArchGDAL v0.4.0 which was just released. I added v0.4 to the compat, but we could also remove ArchGDAL of 0.3.1 to prevent this issue altogether.

**Comment by ViralBShah** [comment]
Let's keep moving forward on versions.

**Comment by vlandau** [comment]
I'll close this. I can do direct commit to master to update the ArchGDAL compat if that works?

**Comment by ViralBShah** [comment]
:-) I also updated IterativeSolvers.jl. Seems to pass things for me - but can you give it a try?

I think these old versions were holding back many dependencies to old versions. This should resolve more dependent packages to use newer versions.

**Comment by ViralBShah** [comment]
Just bumped AlgebraicMultigrid too.

**Comment by vlandau** [comment]
Install working fine on my Linux machine :+1:

**Comment by ViralBShah** [comment]
Let's give it a few days on master and then tag a new version. Do the omniscape tests pass with this?

**Comment by vlandau** [comment]
I'll test it out now!

**Comment by vlandau** [comment]
Ah, we changed RasterMeta internally in Circuitscape so I just need to make a slight update. I'm going to update the Circuitscape dep to 5.6.0 soon,too, and switch to the CS versions of `read_raster` and `write_raster`.

**Pull request closed without merging**
