### PR TITLE
test on windows and julia 1.1

### PR DESCRIPTION
**Pull request by vlandau**
to address appveyor failures mentioned to #223

### CODE REVIEW

**Comment by vlandau** [comment]
Appear to be getting the same failures on Windows in Travis.

**Comment by vlandau** [comment]
Appear to be getting the same failures on Windows in Travis

**Comment by ViralBShah** [comment]
Can you rebase on the latest master?

**Comment by ranjanan** [comment]
Yes, these tests fail on Windows VMs I have tested on as well. Definitely related to #188. Our plan so far is to implement multi-threading to solve this.

**Comment by vlandau** [comment]
> Can you rebase on the latest master?

I should already be up to date with the latest master on this branch

**Comment by vlandau** [comment]
> The failure is the same as #188. Looks like a windows mmap issue - perhaps it is running out of resources or something. @ranjanan Does this test fail when we run it standalone as well?

Let's close this PR then?

**Comment by vlandau** [comment]
> The failure is the same as #188. Looks like a windows mmap issue - perhaps it is running out of resources or something. @ranjanan Does this test fail when we run it standalone as well?

Let's close this PR then?

**Comment by vlandau** [comment]
Noticing windows tests _did_ pass on Julia 1.3 in Travis (I think it didn't pass on 1.3 in Appveyor?)

**Comment by ViralBShah** [comment]
Let's leave it open a little while longer. I'll see if there's an easy fix. @ranjanan Do you want to avoid the use of Travis windows?

**Comment by ViralBShah** [comment]
@vlandau I've made you an owner of the Circuitscape org.

**Comment by ranjanan** [comment]
I've merged this with #225 where I'll reduce the number of tests that I run every single time.

**Pull request closed without merging**
