### PR TITLE
Allow users to switch to 64bit indexing when required

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by ranjanan** [comment]
Meaning they can use `Int64` to index instead of the default `Int32`.

**Comment by ViralBShah** [comment]
That is not what single and double precision means!

**Comment by ViralBShah** [comment]
Also, why should anyone care about this? Can't we just use `Int32` everywhere - or have you encountered problems where we need Int64?

**Comment by ranjanan** [comment]
> That is not what single and double precision means!

True. Will change the title and the name of the option to "use 64-bit indexing". 

> Also, why should anyone care about this? 

I just encountered a problem (~size 400 m) where we need to switch to 64 bit indexing.

**Pull request merged**
