### PR TITLE
Fix some cumulative current map logic

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by merijnvdb** [comment]
Thank you @ranjanan , I'm quite new to Github so I'm not sure where to find the proposed solution? Is it a debugged version of the toolbox, or an output file or something? I can see a lot of coding in #330, but am not sure how to apply this in my arcmap toolbox?

**Comment by merijnvdb** [comment]
I think this solution is in Julia code? I don't have Julia, my problem arose in using the Arcmap toolbox. Is there a fix there too, or should I work in Julia?

**Comment by ranjanan** [comment]
@merijnvdb is it possible to work in Julia at the moment? I have received a few emails about the ArcGIS toolbox, and will debug it soon when I get a copy of ArcGIS. If the Julia version still has the issue, feel free to reopen #327. In the meantime, I shall create a new issue requesting help on the ArcGIS toolbox.

**Comment by merijnvdb** [comment]
@ranjanan  Of course! I am just unsure how to implement the fix because of my infamiliarity with Julia. The code formatting of 875bd85, which I think you made for me to implement, looks different from the formatting in the .ini file I created to run Circuitscape in Julia.

**Comment by ranjanan** [comment]
So you just need to update the Circuitscape version: 

```julia
using Pkg; Pkg.update()
```
`Pkg.status()` should tell you which version of Circuitscape is installed.

If you haven't installed Circuitscape, the way to install it is: 
```julia
using Pkg; Pkg.add("Circuitscape")
```

**Comment by vlandau** [comment]
@merijnvdb it is solving that many pairs because  there are 20506 possible sets of two elements from a set of 434 (i.e. the combinatoric, `434 choose 2`). Would you mind sharing your INI file here so we can take a look?

**Comment by vlandau** [comment]
@merijnvdb can you actually open a new issue? That would be a better place to discuss than this PR. Thanks for bearing with us!

**Comment by merijnvdb** [comment]
Of course, and thanks so much for helping, the new issue is #332

**Pull request merged**
