### PR TITLE
Removed loop for array sum and fixed invalid argument

### PR DESCRIPTION
**Pull request by glaroc**

### CODE REVIEW

**Comment by ViralBShah** [comment]
The loop was supposed to consume lesser memory and be as fast. @ranjanan Can we investigate what's happening?

**Comment by ranjanan** [comment]
It seems that the `branch_currents` variable is not getting inferred correctly by the compiler over [here](https://github.com/Circuitscape/Circuitscape.jl/pull/175/files#diff-196ab0e20a5508faf4f8eff7456a2904L162). This is related to this [open issue](https://github.com/JuliaLang/julia/issues/29363) on the julia project. 

One way around it is adding a function barrier to force inference, which is what `sum` seems to be doing. 

Thanks for the fix!

**Comment by ranjanan** [comment]
The looped code there was allocating way too much because of the inference bug. One solution is to throw that code in a loop, and the other is just calling `sum(x, dims=1)`. Both of them time about the same and allocate about the same, hence I accepted this fix. 

So far, from my experiments it looks like memory usage peaks when I construct the preconditioner (~120 GB on Julia 1.1 and ~95 GB on Julia 1.0.2). But this was with this fix in place.

**Comment by ViralBShah** [comment]
cc @jeffbezanson for the inference problem. Probably captured in other issues on julialang.

**Comment by ViralBShah** [comment]
The comment says that the line fails on windows 32-bit. Still the case?

**Comment by glaroc** [comment]
Note that the line sum(x, 1) was failing on all platforms because the dimension parameter was improperly specified, at least in the current version of Julia. It needs to be sum(x,dims=1).

**Comment by ranjanan** [comment]
@ViralBShah the comment is actually outdated from the version that worked on v0.6. I then removed Win32 support later on 1.0 because of a different weird intermittent CI failure. It looks like I'm now seeing this on Win64 as well (like on this PR). I'm not able to reproduce this error on an actual Win64 machine though.

**Comment by ViralBShah** [comment]
Need to fix the win32 issue as well as inference! Can you help file the relevant issues on julialang?

**Comment by ranjanan** [comment]
The inference bug is already an open issue: https://github.com/JuliaLang/julia/issues/29363.

**Pull request merged**
