### PR TITLE
Use do-blocks for managing rasters via ArchGDAL

### PR DESCRIPTION
**Pull request by yeesian**
That way you clean up the `raw` dataset even in the event of an error.

### CODE REVIEW

**Comment by vlandau** [comment]
@yeesian would you mind merging the master branch back into your patch-2 branch to retrigger CI so we can merge? Thanks for submitting this PR, and sorry for taking so long to get back to you!

**Comment by vlandau** [comment]
Thanks @yeesian! 

@ranjanan @ViralBShah can we go ahead and merge? @yeesian has adjusted the code to use the safer do-block so operations will always clean up after themselves even in the case of an error. This is similar to what is implemented in Omniscape (following a PR there from @yeesian). We should also merge #263.

**Comment by ViralBShah** [comment]
Go for it - but we really need to sort out our CI.

**Comment by ViralBShah** [comment]
Actually can we rebase this on master?

**Comment by vlandau** [comment]
Looks like @yeesian merged the latest commits from master 4 days ago, so it should be all caught up.

**Comment by ViralBShah** [comment]
@vlandau can you merge if you're comfortable?

**Pull request merged**
