### PR TITLE
Added Geotiff input and output functionality with GeoArrays

### PR DESCRIPTION
**Pull request by glaroc**
Adds possibility to use .tif files for habitats and resistances. Adds dependence on GeoArrays, GDAL_jll and CoordinateTransformations packages.

Outputs are in same format as input. If input is .tif, outputs are Float32 geotiffs (GDAL doesn't have a Float16 format for tiffs), keeping reference system.

This significantly accelerates reading times for large files and produces files that are about 33% the size of .asc.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@glaroc Would it be helpful if I gave you commit access?

**Comment by glaroc** [comment]
@ViralBShah Not sure this is necessary for now. The tests are timing out, but I think the code works. Obviously, there are no tests for the geotiff functionalities. If you think there are many more changes to be made, for sure being able to create branches would make it easier for me.

**Comment by vlandau** [comment]
Is it timing out because of Travis or because of Julia? If it's Travis, you can specify a longer length of time to be allowed to pass before timeout.

**Comment by glaroc** [comment]
@vlandau I think it's because of Travis.

**Comment by vlandau** [comment]
Here's an example of `travis_wait` for a Julia test
```
script: travis_wait 30 julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)
```

You should be able to just put that anywhere in the .travis.yml, for example, this [.travis.yml](https://github.com/Circuitscape/Omniscape.jl/blob/d69ee2cc53b06219c9b3109171eda672b65c6cab/.travis.yml)

**Comment by ViralBShah** [comment]
It is just because the tests take too long to run. We need @ranjanan to reduce the number of tests for CI.

**Comment by vlandau** [comment]
The travis timeout has to do with output. A travis timeout would be triggered by default after 10 minutes of no output. I think the overall cap might be 60 minutes?

**Comment by vlandau** [comment]
Actually the hard cutoff is 50 minutes, so looks like that's being confronted. So yes, need fewer tests.
https://stackoverflow.com/questions/32128422/travis-ci-how-is-time-limit-counted-for-builds-sum-of-all-jobs-or-time-of-lo

**Comment by glaroc** [comment]
I think it's timing out after 50 minutes.

**Comment by vlandau** [comment]
> It is just because the tests take too long to run. We need @ranjanan to reduce the number of tests for CI.

@ViralBShah sorry I original read this as "is it" instead of "it is" which is why I brought up the 10 minute time out as a possible reason.

**Comment by vlandau** [comment]
Adding a note here that `GeoArrays.read` also supports reading in .asc files. 

It will probably make sense to get rid of `readdlm` entirely (for a variety of reasons) and just write two wrapper functions (one for `GeoArrays.read` and one for `GeoArays.write`). With those wrapper functions, not much would need to be changed in Circuitscape as it currently is on the master branch. 

We would need to, as @glaroc did, add the affine mapping values and crs to RasterMeta (and these would be added regardless of whether the user was reading from .asc or .tif because `GeoArrays.read` always created them). The only variable that would be needed in addition to those is a flag specifying whether the user wants to write to .tif or .asc

**Comment by vlandau** [comment]
GeoArrays.read() for .asc files also supports handling the .prj files that are somtimes associated with .asc files (the .prj file specifies the cartographic projection)

**Comment by vlandau** [comment]
Tacking this on here since it appears to be _possibly_ related, and wanted to bring it to folks' attention: https://discourse.julialang.org/t/calling-a-function-breaks-repl-in-juno-error-unlock-from-wrong-thread/36165/2

**Comment by glaroc** [comment]
@vlandau I agree that it might make more sense to do all raster i/o through GeoArrays.

**Comment by vlandau** [comment]
Just FYI see #229. I used ArchGDAL only to make it lighter weight, since GeoArrays has a lot of deps, and I was also having precompilation issues with it in Julia 1.4 (name space issues, which seemed to slow down precompilation significantly).

**Comment by ViralBShah** [comment]
Would be good to identify the namespace and precompile issues and at least file them.

**Comment by glaroc** [comment]
There was a small typo in this latest PR that should be fixed now. The tests are failing because they take too long to execute.

**Comment by ViralBShah** [comment]
@ranjanan We should disable the troublesome tests, and maybe separate the tests into having quick CI tests, and a more comprehensive test suite separately.

**Comment by vlandau** [comment]
Should we close this and switch over to #229?

**Pull request closed without merging**
