### PR TITLE
WIP: Multithreading

### PR DESCRIPTION
**Pull request by ranjanan**
Error I'm stuck on just now: when I'm running multi-threaded, I get NaNs for my voltages

### CODE REVIEW

**Comment by ranjanan** [comment]
Steps to reproduce: 
1. Check out Circuitscape with this branch. 
2. Start Julia with multiple threads
3. From the REPL run, `buzz = Ref{Any}()` and `foo = Vector{Any}()`
4. Run `cd(joinpath(pkgdir(Circuitscape), "test")` 
5. Run `compute(test_problem("sgVerify1.ini")`

**Comment by ViralBShah** [comment]
What exactly are you multi-threading here? I couldn't tell from the diff - so would help to have a quick explanation.

**Comment by ranjanan** [comment]
I am trying to spawn several tasks that independently solve linear systems and generate and write current maps

**Comment by ViralBShah** [comment]
@ranjanan Can you document what you tried here and experiments with RR?

**Comment by ranjanan** [comment]
Currently runs but with returns incorrect result on raster pairwise. PR for AMG submitted: https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/pull/68

**Comment by ViralBShah** [comment]
Say I have 4 cores, and hence 4 threads, but I spawn 100 solves. Won't those 100 solves be concurrently updating this data structure, unless you schedule the solves to ensure that each processor is only working on one solve at a time?

I think you need to implement locking in the AMG code, so that each thread that is solving has a lock on the AMG data structure until its job is done, you should get it to work correctly.

**Comment by vlandau** [comment]
I had a similar issue with Omniscape, which is why I had to expand the array along a third dimension, with one slice per thread -- not the most ideal solution memory-wise, but not sure what the lock/unlock overhead might be with so many solves (can be one solve per second or even faster).

**Comment by ViralBShah** [comment]
Seeing errors with SharedArrays makes me feel that we really should just get multi-threading done. I feel like we were really close the last time and need to correctly handle a couple of races in AMG.

**Comment by ranjanan** [comment]
Yes, you are right. Trying to find bandwidth, which is a little elusive.

**Comment by ranjanan** [comment]
Will try to make a push this month

**Pull request closed without merging**
